services:
  - type: web
    name: highrise-music-bot
    runtime: python
    buildCommand: sudo apt-get update && sudo apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: PORT
        value: 3000
